### ISSUE TITLE
crack 1000

### ISSUE THREAD

**Issue by k88936** [A4-Tacks/mindustry_logic_bang_lang#6]
我计划实现一个通用的程序拆分器（by java，生成蓝图的，目的是突破1000限制，用java是因为有现成的生成蓝图的库，但什么时候完成没准）

想给bang实现一个，但是:
1. 我不懂rust没读过源码，想知道bang**非内联**调用函数的机制.
2. rust和java，我目前想到的方法是让bang语言编译输出**在注释里增加一些必要的信息**，然后java去解析

**Comment by A4-Tacks** [comment]
bang并没有非内联函数，确切地说连函数都没有。

我们将DExp放入const，并且使用传参约定进行const的替换也就是内联，并使用take求值，这是不着痕迹的。

如果你说的是`examples/caller.mdtlbl`的话，那么你可以看出，只是使用const-DExp设置了返回值并跳转到了某段不会直接执行的代码。

编译输出必要的信息的话，我也没有想到好的实现。

**Comment by A4-Tacks** [comment]
程序拆分的话，或许可以约定一些特殊格式的语句，我们有`ReprVar`，也就是`'@&/;!*"'`这种形式的值，
所以不用担心编译输出的语句格式问题。

那么我们就可以约定一些原版几乎不可能添加的语句格式来手动编写与你的拆分器互动的语句，
然后拆分器根据这些语句提供的信息完成拆分。

如果进行分割、语句消去则需要注意一些事，以下为不完全列举：

- 在`select`语句 (`switch`对应的更原始的格式) 这些行数重相关的语句中不能进行拆分与增减语句条数
- 在有跳转线经过的区段 (并不是为了进行对可拆分的函数进行调用的跳转行为) 不能进行拆分

**Comment by k88936** [comment]
> #examples/caller.mdtlbl                   # 如果进行分割、语句消去则需要注意一些事

我只能去拆分类似函数的代码块，还做不到直接去分析程序或者“函数”里的细节

> 编译输出必要的信息的话

如果
```
const Foo = (
    take Msg = _0; # 求值出需要传递的
    take A = _1;
    take B = _2;

    const Self = Fun_Foo;

    Self.Msg Self.A Self.B = Msg A B; # 传递值
    op Self.back @counter + 1; # 设置返回地址
    goto :fun_foo_head _; # call
);
```
可以通过宏替换(需要根据Foo位置的string替换goto的label)比如
```
call Foo 123 234
```
支持，那么可以加一些不会被跳转到的label，里面提供一些信息

> 语句格式来手动编写与你的拆分器互动的语句

这样也好但需要修改bang本身，，，

**Comment by A4-Tacks** [comment]
> > #examples/caller.mdtlbl                   # 如果进行分割、语句消去则需要注意一些事
> 
> 我只能去拆分类似函数的代码块，还做不到直接去分析程序或者“函数”里的细节
> 
> > 编译输出必要的信息的话
> 
> 如果
> 
> ```
> const Foo = (
>     take Msg = _0; # 求值出需要传递的
>     take A = _1;
>     take B = _2;
> 
>     const Self = Fun_Foo;
> 
>     Self.Msg Self.A Self.B = Msg A B; # 传递值
>     op Self.back @counter + 1; # 设置返回地址
>     goto :fun_foo_head _; # call
> );
> ```
> 
> 可以通过宏替换(需要根据Foo位置的string替换goto的label)比如
> 
> ```
> call Foo 123 234
> ```
> 
> 支持，那么可以加一些不会被跳转到的label，里面提供一些信息
> 
> > 语句格式来手动编写与你的拆分器互动的语句
> 
> 这样也好但需要修改bang本身，，，

既然无法完成分析细节，那么使用之前的方案，手动键入元语句，来与您的分割器互动，这个主意怎么样？

我还是不希望为此更改bang，它的负重已经很多了

**Comment by k88936** [comment]
> 手动键入元语句
当然好啊可以给我个例子吗

**Comment by A4-Tacks** [comment]
> 

例如我们可以约定由`**`开头的指令与你的分割器交互，而我们利用原始标识符可以做到这点。

考虑以下代码
```
'**doSplit' 123 456;
'**funBegin' foo param1;
print "foo";
'**funEnd';
```
这在c选项下会产生如下编译结果:
```
**doSplit 123 456
**funBegin foo param1
print "foo"
**funEnd
```

由于原始标识符的存在，我们可以键入除双引号外任意由非空字符组成的标识符，这可以用来与您的分割工具进行交互。

而这些特殊的交互语句，您的分割工具有必要将它们删除，并重新处理跳转关系。

**Comment by k88936** [comment]
好我们约定一下

1. 对于类似caller例子里函数调用

```
skip _ { # 跳过这段函数
    '**extern' Fun_Foo;
    :fun_foo_head # 用于被调用的函数头部标记
    #参数传递
    const Self = Fun_Foo;
    take Msg = Self.Msg;
    take A = Self.A;
    take B = Self.B;

    #方法体
    print Msg (op $ A + B;);
    @counter = Self.back; # 返回到地址
}

```例子里没给编译结果，但我猜测take A = Self.A;会被编译成set bla blabla_bind__A这样我根据skip生成的jump always和set带bind的语句去提取方法体和参数列表   应该可以支持多个函数出口
bang里函数标准的写法我们可以再讨论，但这个我觉得很好了
2. 对于一块顺序执行或者跳转只在内部的代码片段
```
  '**extern' ;#是这么写吧 ：p

blabla
blabla

```
我会根据编译后的代码去分析哪些变量是参数哪些是返回值。这样更加灵活一些。

**Comment by k88936** [comment]
我注意到skip等语句编译的是jump 行号 ...，如果进行拆分那么行数的改变会破坏这些结果，我认为这里bang需要使用label

**Comment by A4-Tacks** [comment]
> 我注意到skip等语句编译的是jump 行号 ...，如果进行拆分那么行数的改变会破坏这些结果，我认为这里bang需要使用label

有的，你可以仔细看一看help, 观察编译目标`MdtTagCode`

**Comment by A4-Tacks** [comment]
> 好我们约定一下
> 
> 1. 对于类似caller例子里函数调用
> 
> ```
> skip _ { # 跳过这段函数
>     '**extern' Fun_Foo;
>     :fun_foo_head # 用于被调用的函数头部标记
>     #参数传递
>     const Self = Fun_Foo;
>     take Msg = Self.Msg;
>     take A = Self.A;
>     take B = Self.B;
> 
>     #方法体
>     print Msg (op $ A + B;);
>     @counter = Self.back; # 返回到地址
> }
> ```
> 
> 例子里没给编译结果，但我猜测take A = Self.A;会被编译成set bla blabla_bind__A这样我根据skip生成的jump always和set带bind的语句去提取方法体和参数列表而且可以支持多个函数出口 bang里函数标准的写法我们可以再讨论，但这个我觉得很好了 2. 对于一块顺序执行或者跳转只在内部的代码片段
> 
> ```
>     '**extern' ;#是这么写吧 ：p
>     set   bla 3
>     set    blabla 2
> ```
> 
> 我会根据编译后的代码去分析哪些变量是参数哪些是返回值。这样更加灵活一些。

实际上take是零开销的，并不会自己生成一个set。release有编译完成的二进制程序，你可以将它下载到本地进行测试。

`take A = Self.A;`这一句在生成的代码层面上其实啥也没做，因为`Self.A`的句柄就是它本身，也就是`__...__bind...`的格式，
take的作用只不过是将`Self.A`求出句柄，并生成一个`const A =`到这个句柄，并没有生成一个set语句。

我猜你没有仔细看示例中的take原理

**Comment by k88936** [comment]
get it.
写了个返回值的，体会到bang的妙  : )
```

const Fun_Foo = fun_Foo;
const Add = (
    
    take A = _0;
    take B = _1;

    const Self = Fun_Foo;

    Self.A Self.B = A B; # 传递值
	
    op Self.back @counter + 1; # 设置返回地址
    goto :fun_add_head _; # call
	$ = Self.Ret;
	
);
skip _ { # 跳过这段函数
    '**extern' Fun_Foo;
    :fun_add_head # 用于被调用的函数头部标记
    const Self = Fun_Add;
    take A = Self.A;
    take B = Self.B;
    op Self.Ret A + B;#返回值
    @counter = Self.back; # 返回到地址
}
take[1 2] ret = Add;
print ret;

```

> 2. 对于一块顺序执行或者跳转只在内部的代码片段
    '**externBegin' ;#是这么写吧 ：p
    set   bla 3
    set    blabla 2
    '**externEnd' ;
这里落了end
